# sympy_codegen_bw_fullkernel.py
# ------------------------------------------------------------
# Generates CUDA code for Baraff-Witkin triangle energy with:
#   Inputs per instance: x_in (9), r_in (9)
#   All rest values computed inside kernel: rotation->UV->M->Minv, area
#   SymPy-generated gradient/Hessian w.r.t. x computed in the same kernel
#
# Output:
#   - bw_grad_kernel_full: grad only
#   - bw_hess_kernel_full: hess only
#   - main(): alloc dummy x/r, run+time both with CUDA events
# ------------------------------------------------------------

import sympy as sp
from sympy.printing.c import C99CodePrinter
printer = C99CodePrinter()

# ----------------------------
# SymPy: Energy in terms of x and (m00,m01,m10,m11, area)
# Those symbols will be computed as locals inside CUDA kernel.
# ----------------------------
x = sp.Matrix(sp.symbols("x0:9", real=True))

# current verts
p0 = sp.Matrix([x[0], x[1], x[2]])
p1 = sp.Matrix([x[3], x[4], x[5]])
p2 = sp.Matrix([x[6], x[7], x[8]])

e10 = p1 - p0
e20 = p2 - p0
F = sp.Matrix.hstack(e10, e20)  # 3x2

m00, m01, m10, m11 = sp.symbols("m00 m01 m10 m11", real=True)
area = sp.Symbol("area", real=True)
stretchS = sp.Symbol("stretchS", real=True)
shearS   = sp.Symbol("shearS", real=True)

Minv = sp.Matrix([[m00, m01],
                  [m10, m11]])

c0 = F * Minv[:, 0]  # (3,)
c1 = F * Minv[:, 1]  # (3,)

def dot3(a,b): return a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
def norm3(a):  return sp.sqrt(dot3(a,a))

I5u = norm3(c0)
I5v = norm3(c1)
I6  = dot3(c0, c1)

stretch_energy = (I5u - 1)**2 + (I5v - 1)**2
shear_energy   = (I6)**2

E = area * (stretchS * stretch_energy + shearS * shear_energy)

g = sp.Matrix([sp.diff(E, xi) for xi in x])  # 9
H = g.jacobian(x)                             # 9x9

# CSE separately (kernels independent)
g_repls, g_red = sp.cse(list(g), optimizations="basic")
H_repls, H_red = sp.cse(list(H), optimizations="basic")  # 81 row-major

def cexpr(expr): return printer.doprint(expr)
def emit_assign(sym, expr, indent="    "):
    return f"{indent}const double {sym} = {cexpr(expr)};"

# ----------------------------
# Emit CUDA .cu
# ----------------------------
print(r"""// Auto-generated by sympy_codegen_bw_fullkernel.py
#include <cuda_runtime.h>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <vector>

#ifndef CHECK_CUDA
#define CHECK_CUDA(call) do {                                 \
  cudaError_t err = call;                                     \
  if (err != cudaSuccess) {                                   \
    fprintf(stderr, "CUDA error %s:%d: %s\n",                 \
            __FILE__, __LINE__, cudaGetErrorString(err));     \
    std::exit(1);                                             \
  }                                                           \
} while(0)
#endif

// Inputs:
//   x_in: N*9 doubles (current triangle positions: p0,p1,p2)
//   r_in: N*9 doubles (rest triangle positions:    r0,r1,r2)
//
// Outputs:
//   g_out: N*9 doubles
//   H_out: N*81 doubles (row-major 9x9)
//
// The kernel computes rest UV frame + Minv + area internally.
// No precomputed Minv/area are passed in.
""")

print(r"""
__device__ __forceinline__ void cross3(double ax,double ay,double az,
                                       double bx,double by,double bz,
                                       double &cx,double &cy,double &cz){
  cx = ay*bz - az*by;
  cy = az*bx - ax*bz;
  cz = ax*by - ay*bx;
}
__device__ __forceinline__ double dot3(double ax,double ay,double az,
                                      double bx,double by,double bz){
  return ax*bx + ay*by + az*bz;
}
__device__ __forceinline__ double norm3(double ax,double ay,double az){
  return ::sqrt(dot3(ax,ay,az,bx=0,by=0,bz=0)); // dummy, will not be used
}
""".replace("return ::sqrt(dot3(ax,ay,az,bx=0,by=0,bz=0));",
            "return ::sqrt(ax*ax + ay*ay + az*az);"))

print(r"""
__device__ __forceinline__ void mat3_mul_vec3(
    const double R[9], double vx,double vy,double vz,
    double &ox,double &oy,double &oz)
{
  ox = R[0]*vx + R[1]*vy + R[2]*vz;
  oy = R[3]*vx + R[4]*vy + R[5]*vz;
  oz = R[6]*vx + R[7]*vy + R[8]*vz;
}

// Rodrigues-like rotation used in your JAX/PyTorch rest-shape:
// R = I + K + K^2/(1+cos)
__device__ __forceinline__ void build_rest_rotation(
    double n0,double n1,double n2,   // unit normal
    double R[9])
{
  // target = (0,1,0)
  const double t0=0.0, t1=1.0, t2=0.0;

  // vec = n x target
  double vx,vy,vz;
  cross3(n0,n1,n2, t0,t1,t2, vx,vy,vz);

  const double cosv = n0*t0 + n1*t1 + n2*t2;

  // K (skew)
  const double K00=0.0,   K01=-vz,  K02= vy;
  const double K10= vz,   K11=0.0,  K12=-vx;
  const double K20=-vy,   K21= vx,  K22=0.0;

  // K^2
  const double K2_00 = K00*K00 + K01*K10 + K02*K20;
  const double K2_01 = K00*K01 + K01*K11 + K02*K21;
  const double K2_02 = K00*K02 + K01*K12 + K02*K22;

  const double K2_10 = K10*K00 + K11*K10 + K12*K20;
  const double K2_11 = K10*K01 + K11*K11 + K12*K21;
  const double K2_12 = K10*K02 + K11*K12 + K12*K22;

  const double K2_20 = K20*K00 + K21*K10 + K22*K20;
  const double K2_21 = K20*K01 + K21*K11 + K22*K21;
  const double K2_22 = K20*K02 + K21*K12 + K22*K22;

  const double denom = 1.0 + cosv + 1e-8;

  // R = I + K + K^2/denom
  R[0] = 1.0 + K00 + K2_00/denom;
  R[1] = 0.0 + K01 + K2_01/denom;
  R[2] = 0.0 + K02 + K2_02/denom;

  R[3] = 0.0 + K10 + K2_10/denom;
  R[4] = 1.0 + K11 + K2_11/denom;
  R[5] = 0.0 + K12 + K2_12/denom;

  R[6] = 0.0 + K20 + K2_20/denom;
  R[7] = 0.0 + K21 + K2_21/denom;
  R[8] = 1.0 + K22 + K2_22/denom;
}

// Compute Minv (2x2) and area from rest triangle r0,r1,r2.
// Matches your rest-shape construction (rotate to make normal align to Y, use x,z as uv).
__device__ __forceinline__ void rest_minv_area(
    double r0x,double r0y,double r0z,
    double r1x,double r1y,double r1z,
    double r2x,double r2y,double r2z,
    double thickness,
    double &m00,double &m01,double &m10,double &m11,
    double &area)
{
  // area (rest)
  double e01x=r1x-r0x, e01y=r1y-r0y, e01z=r1z-r0z;
  double e02x=r2x-r0x, e02y=r2y-r0y, e02z=r2z-r0z;
  double cx,cy,cz;
  cross3(e01x,e01y,e01z, e02x,e02y,e02z, cx,cy,cz);
  const double nlen = ::sqrt(cx*cx + cy*cy + cz*cz) + 1e-8;
  area = thickness * 0.5 * nlen;

  // unit normal
  const double nx = cx / nlen;
  const double ny = cy / nlen;
  const double nz = cz / nlen;

  // rotation
  double R[9];
  build_rest_rotation(nx,ny,nz, R);

  // rotate r0,r1,r2
  double rr0x,rr0y,rr0z, rr1x,rr1y,rr1z, rr2x,rr2y,rr2z;
  mat3_mul_vec3(R, r0x,r0y,r0z, rr0x,rr0y,rr0z);
  mat3_mul_vec3(R, r1x,r1y,r1z, rr1x,rr1y,rr1z);
  mat3_mul_vec3(R, r2x,r2y,r2z, rr2x,rr2y,rr2z);

  // uv = (x,z)
  const double u0x=rr0x, u0y=rr0z;
  const double u1x=rr1x, u1y=rr1z;
  const double u2x=rr2x, u2y=rr2z;

  // M = [u1-u0, u2-u0] columns (2x2)
  const double a00 = (u1x - u0x);
  const double a10 = (u1y - u0y);
  const double a01 = (u2x - u0x);
  const double a11 = (u2y - u0y);

  const double det = a00*a11 - a01*a10;
  const double invdet = 1.0 / (det + 1e-12);

  // Minv = inv(M) row-major
  m00 =  a11 * invdet;
  m01 = -a01 * invdet;
  m10 = -a10 * invdet;
  m11 =  a00 * invdet;
}
""")

# ----------------------------
# Gradient kernel (inputs: x_in, r_in only)
# ----------------------------
print(r"""
__global__ void bw_grad_kernel_full(
    const double* __restrict__ x_in,
    const double* __restrict__ r_in,
    double stretchS, double shearS,
    double thickness,
    double* __restrict__ g_out,
    int N)
{
    const int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= N) return;

    // current x
    const double x0 = x_in[i*9 + 0];
    const double x1 = x_in[i*9 + 1];
    const double x2 = x_in[i*9 + 2];
    const double x3 = x_in[i*9 + 3];
    const double x4 = x_in[i*9 + 4];
    const double x5 = x_in[i*9 + 5];
    const double x6 = x_in[i*9 + 6];
    const double x7 = x_in[i*9 + 7];
    const double x8 = x_in[i*9 + 8];

    // rest r
    const double r0x = r_in[i*9 + 0];
    const double r0y = r_in[i*9 + 1];
    const double r0z = r_in[i*9 + 2];
    const double r1x = r_in[i*9 + 3];
    const double r1y = r_in[i*9 + 4];
    const double r1z = r_in[i*9 + 5];
    const double r2x = r_in[i*9 + 6];
    const double r2y = r_in[i*9 + 7];
    const double r2z = r_in[i*9 + 8];

    double m00,m01,m10,m11, area;
    rest_minv_area(r0x,r0y,r0z, r1x,r1y,r1z, r2x,r2y,r2z,
                   thickness, m00,m01,m10,m11, area);

    // ---- CSE (grad) from SymPy ----
""")
for sym, expr in g_repls:
    print(emit_assign(str(sym), expr))
print(r"""
    // write grad
""")
for k in range(9):
    print(f"    g_out[i*9 + {k}] = {cexpr(g_red[k])};")
print("}\n")

# ----------------------------
# Hessian kernel (inputs: x_in, r_in only)
# ----------------------------
print(r"""
__global__ void bw_hess_kernel_full(
    const double* __restrict__ x_in,
    const double* __restrict__ r_in,
    double stretchS, double shearS,
    double thickness,
    double* __restrict__ H_out,
    int N)
{
    const int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= N) return;

    const double x0 = x_in[i*9 + 0];
    const double x1 = x_in[i*9 + 1];
    const double x2 = x_in[i*9 + 2];
    const double x3 = x_in[i*9 + 3];
    const double x4 = x_in[i*9 + 4];
    const double x5 = x_in[i*9 + 5];
    const double x6 = x_in[i*9 + 6];
    const double x7 = x_in[i*9 + 7];
    const double x8 = x_in[i*9 + 8];

    const double r0x = r_in[i*9 + 0];
    const double r0y = r_in[i*9 + 1];
    const double r0z = r_in[i*9 + 2];
    const double r1x = r_in[i*9 + 3];
    const double r1y = r_in[i*9 + 4];
    const double r1z = r_in[i*9 + 5];
    const double r2x = r_in[i*9 + 6];
    const double r2y = r_in[i*9 + 7];
    const double r2z = r_in[i*9 + 8];

    double m00,m01,m10,m11, area;
    rest_minv_area(r0x,r0y,r0z, r1x,r1y,r1z, r2x,r2y,r2z,
                   thickness, m00,m01,m10,m11, area);

    // ---- CSE (hess) from SymPy ----
""")
for sym, expr in H_repls:
    print(emit_assign(str(sym), expr))
print(r"""
    // write Hessian (row-major 9x9)
""")
for idx in range(81):
    print(f"    H_out[i*81 + {idx}] = {cexpr(H_red[idx])};")
print("}\n")

# Timing + main
print(r"""
static float time_grad(
    const double* d_x, const double* d_r,
    double stretchS, double shearS, double thickness,
    double* d_g, int N, int warmup, int iters)
{
    const int threads = 256;
    const int blocks = (N + threads - 1) / threads;

    for(int k=0;k<warmup;++k)
        bw_grad_kernel_full<<<blocks,threads>>>(d_x,d_r,stretchS,shearS,thickness,d_g,N);
    CHECK_CUDA(cudaGetLastError());
    CHECK_CUDA(cudaDeviceSynchronize());

    cudaEvent_t s,e; CHECK_CUDA(cudaEventCreate(&s)); CHECK_CUDA(cudaEventCreate(&e));
    CHECK_CUDA(cudaEventRecord(s));
    for(int k=0;k<iters;++k)
        bw_grad_kernel_full<<<blocks,threads>>>(d_x,d_r,stretchS,shearS,thickness,d_g,N);
    CHECK_CUDA(cudaEventRecord(e));
    CHECK_CUDA(cudaEventSynchronize(e));

    float ms=0; CHECK_CUDA(cudaEventElapsedTime(&ms,s,e));
    cudaEventDestroy(s); cudaEventDestroy(e);
    return ms/iters;
}

static float time_hess(
    const double* d_x, const double* d_r,
    double stretchS, double shearS, double thickness,
    double* d_H, int N, int warmup, int iters)
{
    const int threads = 256;
    const int blocks = (N + threads - 1) / threads;

    for(int k=0;k<warmup;++k)
        bw_hess_kernel_full<<<blocks,threads>>>(d_x,d_r,stretchS,shearS,thickness,d_H,N);
    CHECK_CUDA(cudaGetLastError());
    CHECK_CUDA(cudaDeviceSynchronize());

    cudaEvent_t s,e; CHECK_CUDA(cudaEventCreate(&s)); CHECK_CUDA(cudaEventCreate(&e));
    CHECK_CUDA(cudaEventRecord(s));
    for(int k=0;k<iters;++k)
        bw_hess_kernel_full<<<blocks,threads>>>(d_x,d_r,stretchS,shearS,thickness,d_H,N);
    CHECK_CUDA(cudaEventRecord(e));
    CHECK_CUDA(cudaEventSynchronize(e));

    float ms=0; CHECK_CUDA(cudaEventElapsedTime(&ms,s,e));
    cudaEventDestroy(s); cudaEventDestroy(e);
    return ms/iters;
}

int main(){
    const int N = 20000;
    const double stretchS = 2000.0;
    const double shearS   = 1000.0;
    const double thickness = 0.01;

    // Dummy init x and r (you should replace with real mesh data)
    std::vector<double> h_x(N*9, 0.0);
    std::vector<double> h_r(N*9, 0.0);

    for(int i=0;i<N;++i){
        // current
        for(int k=0;k<9;++k) h_x[i*9+k] = 0.01*(k+1);
        // rest triangle (non-degenerate)
        h_r[i*9+0] = 0.0; h_r[i*9+1] = 0.0; h_r[i*9+2] = 0.0;
        h_r[i*9+3] = 1.0; h_r[i*9+4] = 0.0; h_r[i*9+5] = 0.0;
        h_r[i*9+6] = 0.0; h_r[i*9+7] = 0.0; h_r[i*9+8] = 1.0;
    }

    double *d_x=nullptr, *d_r=nullptr, *d_g=nullptr, *d_H=nullptr;
    CHECK_CUDA(cudaMalloc(&d_x, sizeof(double)*h_x.size()));
    CHECK_CUDA(cudaMalloc(&d_r, sizeof(double)*h_r.size()));
    CHECK_CUDA(cudaMalloc(&d_g, sizeof(double)*N*9));
    CHECK_CUDA(cudaMalloc(&d_H, sizeof(double)*N*81));

    CHECK_CUDA(cudaMemcpy(d_x, h_x.data(), sizeof(double)*h_x.size(), cudaMemcpyHostToDevice));
    CHECK_CUDA(cudaMemcpy(d_r, h_r.data(), sizeof(double)*h_r.size(), cudaMemcpyHostToDevice));

    const int warmup = 5, it_g=50, it_H=20;

    const float g_ms = time_grad(d_x,d_r,stretchS,shearS,thickness,d_g,N,warmup,it_g);
    const float H_ms = time_hess(d_x,d_r,stretchS,shearS,thickness,d_H,N,warmup,it_H);

    printf("N=%d\n", N);
    printf("grad: %.6f ms/call  (%.3f ns/tri)\n", g_ms, (g_ms*1e6)/N);
    printf("hess: %.6f ms/call  (%.3f ns/tri)\n", H_ms, (H_ms*1e6)/N);

    cudaFree(d_x); cudaFree(d_r); cudaFree(d_g); cudaFree(d_H);
    return 0;
}
""")
