# sympy_codegen_bending_cuda_separate.py
# ------------------------------------------------------------
# Generates a CUDA .cu file for the *bending energy* you used:
#
#   theta(x) = 2 * atan2( ((n0 x n1) · axis)/||axis|| , (n0·n1 + ||n0|| ||n1||) )
#   E(x) = bendStiff * (theta(x) - t_init)^2 * edge_len
#
# where:
#   n0 = (q0 - q2) x (q1 - q2)
#   n1 = (q1 - q3) x (q0 - q3)
#   axis = (q1 - q0)
# and q0..q3 are the 4 vertices from x (12 DOFs).
#
# Inputs per instance:
#   x_in       : (N,12) doubles
#   t_init_in  : (N,)   doubles   (precomputed rest theta, detached)
#   edge_len_in: (N,)   doubles   (precomputed rest edge length, detached)
#   bendStiff  : scalar double
#
# Outputs:
#   g_out: (N,12) doubles  (gradient)
#   H_out: (N,144) doubles (Hessian 12x12 row-major)
#
# Generates TWO kernels:
#   - bending_grad_kernel : gradient only
#   - bending_hess_kernel : Hessian only
# and times them with CUDA events over N instances.
#
# Usage:
#   python sympy_codegen_bending_cuda_separate.py > bending_separate.cu
#
# Compile:
#   nvcc -O3 -std=c++17 -arch=sm_86 bending_separate.cu -o bending_separate
#
# Run:
#   ./bending_separate
#
# Notes:
# - Full Hessian storage is large (144 doubles/instance).
# - This is purely codegen; you can drop kernels into your own pipeline.
# ------------------------------------------------------------

import sympy as sp
from sympy.printing.c import C99CodePrinter

printer = C99CodePrinter()

# ----------------------------
# Symbols
# ----------------------------
x = sp.Matrix(sp.symbols("x0:12", real=True))  # 12 DOFs
t_init = sp.Symbol("t_init", real=True)
edge_len = sp.Symbol("edge_len", real=True)
bendStiff = sp.Symbol("bendStiff", real=True)
eps = sp.Symbol("eps", real=True)

# ----------------------------
# Helpers
# ----------------------------
def vec3(a, b, c):
    return sp.Matrix([a, b, c])

def cross(a, b):
    return sp.Matrix([
        a[1]*b[2] - a[2]*b[1],
        a[2]*b[0] - a[0]*b[2],
        a[0]*b[1] - a[1]*b[0],
    ])

def dot(a, b):
    return (a[0]*b[0] + a[1]*b[1] + a[2]*b[2])

def norm(a):
    return sp.sqrt(dot(a, a))

# ----------------------------
# Unpack x into q0..q3 (each 3D)
# ----------------------------
q0 = vec3(x[0],  x[1],  x[2])
q1 = vec3(x[3],  x[4],  x[5])
q2 = vec3(x[6],  x[7],  x[8])
q3 = vec3(x[9],  x[10], x[11])

# n0, n1, axis
n0 = cross(q0 - q2, q1 - q2)
n1 = cross(q1 - q3, q0 - q3)
axis = (q1 - q0)

# angle formula (matches your PyTorch)
cross_n0n1 = cross(n0, n1)
cross_dot_axis = dot(cross_n0n1, axis)
axis_norm = norm(axis) + eps
numerator = cross_dot_axis / axis_norm

denominator = dot(n0, n1) + norm(n0) * norm(n1)
theta = 2.0 * sp.atan2(numerator, denominator)

E = bendStiff * (theta - t_init)**2 * edge_len

# Gradient / Hessian wrt x
g = sp.Matrix([sp.diff(E, xi) for xi in x])  # (12,1)
H = g.jacobian(x)                             # (12,12)

# ----------------------------
# CSE separately for grad and Hessian (kernels independent)
# ----------------------------
g_repls, g_red = sp.cse(list(g), optimizations="basic")
H_repls, H_red = sp.cse(list(H), optimizations="basic")  # length 144 in row-major

def cexpr(expr):
    return printer.doprint(expr)

def emit_assign(sym, expr, indent="    "):
    return f"{indent}const double {sym} = {cexpr(expr)};"

# ----------------------------
# Emit CUDA .cu
# ----------------------------
print(r"""// Auto-generated by sympy_codegen_bending_cuda_separate.py
#include <cuda_runtime.h>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <vector>

#ifndef CHECK_CUDA
#define CHECK_CUDA(call) do {                                 \
  cudaError_t err = call;                                     \
  if (err != cudaSuccess) {                                   \
    fprintf(stderr, "CUDA error %s:%d: %s\n",                 \
            __FILE__, __LINE__, cudaGetErrorString(err));     \
    std::exit(1);                                             \
  }                                                           \
} while(0)
#endif

// Layout assumptions:
// x_in        : N * 12 doubles (row-major): x_in[i*12 + k]
// t_init_in   : N doubles
// edge_len_in : N doubles
// g_out       : N * 12 doubles
// H_out       : N * 144 doubles (row-major 12x12): H_out[i*144 + r*12 + c]
""")

# ----------------------------
# Gradient kernel
# ----------------------------
print(r"""
__global__ void bending_grad_kernel(
    const double* __restrict__ x_in,
    const double* __restrict__ t_init_in,
    const double* __restrict__ edge_len_in,
    double bendStiff,
    double eps,
    double* __restrict__ g_out,
    int N)
{
    const int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= N) return;

    // Load x
    const double x0  = x_in[i*12 + 0];
    const double x1  = x_in[i*12 + 1];
    const double x2  = x_in[i*12 + 2];
    const double x3  = x_in[i*12 + 3];
    const double x4  = x_in[i*12 + 4];
    const double x5  = x_in[i*12 + 5];
    const double x6  = x_in[i*12 + 6];
    const double x7  = x_in[i*12 + 7];
    const double x8  = x_in[i*12 + 8];
    const double x9  = x_in[i*12 + 9];
    const double x10 = x_in[i*12 + 10];
    const double x11 = x_in[i*12 + 11];

    const double t_init = t_init_in[i];
    const double edge_len = edge_len_in[i];

    // ---- common subexpressions (grad) ----
""")
for sym, expr in g_repls:
    print(emit_assign(str(sym), expr))

print(r"""
    // ---- write gradient ----
""")
for k in range(12):
    print(f"    g_out[i*12 + {k}] = {cexpr(g_red[k])};")
print("}\n")

# ----------------------------
# Hessian kernel
# ----------------------------
print(r"""
__global__ void bending_hess_kernel(
    const double* __restrict__ x_in,
    const double* __restrict__ t_init_in,
    const double* __restrict__ edge_len_in,
    double bendStiff,
    double eps,
    double* __restrict__ H_out,
    int N)
{
    const int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= N) return;

    // Load x
    const double x0  = x_in[i*12 + 0];
    const double x1  = x_in[i*12 + 1];
    const double x2  = x_in[i*12 + 2];
    const double x3  = x_in[i*12 + 3];
    const double x4  = x_in[i*12 + 4];
    const double x5  = x_in[i*12 + 5];
    const double x6  = x_in[i*12 + 6];
    const double x7  = x_in[i*12 + 7];
    const double x8  = x_in[i*12 + 8];
    const double x9  = x_in[i*12 + 9];
    const double x10 = x_in[i*12 + 10];
    const double x11 = x_in[i*12 + 11];

    const double t_init = t_init_in[i];
    const double edge_len = edge_len_in[i];

    // ---- common subexpressions (hess) ----
""")
for sym, expr in H_repls:
    print(emit_assign(str(sym), expr))

print(r"""
    // ---- write Hessian (row-major 12x12) ----
""")
for idx in range(144):
    print(f"    H_out[i*144 + {idx}] = {cexpr(H_red[idx])};")
print("}\n")

# ----------------------------
# Timing helpers + main()
# ----------------------------
print(r"""
static float time_kernel_grad(
    const double* d_x,
    const double* d_tinit,
    const double* d_elen,
    double bendStiff,
    double eps,
    double* d_g,
    int N, int warmup, int iters)
{
    const int threads = 256;
    const int blocks = (N + threads - 1) / threads;

    for (int k = 0; k < warmup; ++k)
        bending_grad_kernel<<<blocks, threads>>>(d_x, d_tinit, d_elen, bendStiff, eps, d_g, N);
    CHECK_CUDA(cudaGetLastError());
    CHECK_CUDA(cudaDeviceSynchronize());

    cudaEvent_t start, stop;
    CHECK_CUDA(cudaEventCreate(&start));
    CHECK_CUDA(cudaEventCreate(&stop));
    CHECK_CUDA(cudaEventRecord(start));

    for (int k = 0; k < iters; ++k)
        bending_grad_kernel<<<blocks, threads>>>(d_x, d_tinit, d_elen, bendStiff, eps, d_g, N);

    CHECK_CUDA(cudaEventRecord(stop));
    CHECK_CUDA(cudaEventSynchronize(stop));

    float ms = 0.0f;
    CHECK_CUDA(cudaEventElapsedTime(&ms, start, stop));
    CHECK_CUDA(cudaEventDestroy(start));
    CHECK_CUDA(cudaEventDestroy(stop));
    return ms / iters;
}

static float time_kernel_hess(
    const double* d_x,
    const double* d_tinit,
    const double* d_elen,
    double bendStiff,
    double eps,
    double* d_H,
    int N, int warmup, int iters)
{
    const int threads = 256;
    const int blocks = (N + threads - 1) / threads;

    for (int k = 0; k < warmup; ++k)
        bending_hess_kernel<<<blocks, threads>>>(d_x, d_tinit, d_elen, bendStiff, eps, d_H, N);
    CHECK_CUDA(cudaGetLastError());
    CHECK_CUDA(cudaDeviceSynchronize());

    cudaEvent_t start, stop;
    CHECK_CUDA(cudaEventCreate(&start));
    CHECK_CUDA(cudaEventCreate(&stop));
    CHECK_CUDA(cudaEventRecord(start));

    for (int k = 0; k < iters; ++k)
        bending_hess_kernel<<<blocks, threads>>>(d_x, d_tinit, d_elen, bendStiff, eps, d_H, N);

    CHECK_CUDA(cudaEventRecord(stop));
    CHECK_CUDA(cudaEventSynchronize(stop));

    float ms = 0.0f;
    CHECK_CUDA(cudaEventElapsedTime(&ms, start, stop));
    CHECK_CUDA(cudaEventDestroy(start));
    CHECK_CUDA(cudaEventDestroy(stop));
    return ms / iters;
}

int main() {
    const int N = 104065;        // match your benchmark if you want
    const double bendStiff = 1000.0;
    const double eps = 1e-8;

    // Dummy host init: x = small values, t_init = 0, edge_len = 1
    std::vector<double> h_x(N * 12, 0.0);
    std::vector<double> h_tinit(N, 0.0);
    std::vector<double> h_elen(N, 1.0);

    for (int i = 0; i < N; ++i) {
        for (int k = 0; k < 12; ++k) h_x[i*12 + k] = 0.01 * (k + 1);
        h_tinit[i] = 0.0;
        h_elen[i]  = 1.0;
    }

    // Device buffers
    double *d_x=nullptr, *d_tinit=nullptr, *d_elen=nullptr, *d_g=nullptr, *d_H=nullptr;
    CHECK_CUDA(cudaMalloc(&d_x,     sizeof(double) * h_x.size()));
    CHECK_CUDA(cudaMalloc(&d_tinit, sizeof(double) * h_tinit.size()));
    CHECK_CUDA(cudaMalloc(&d_elen,  sizeof(double) * h_elen.size()));
    CHECK_CUDA(cudaMalloc(&d_g,     sizeof(double) * N * 12));
    CHECK_CUDA(cudaMalloc(&d_H,     sizeof(double) * N * 144));

    CHECK_CUDA(cudaMemcpy(d_x,     h_x.data(),     sizeof(double) * h_x.size(),     cudaMemcpyHostToDevice));
    CHECK_CUDA(cudaMemcpy(d_tinit, h_tinit.data(), sizeof(double) * h_tinit.size(), cudaMemcpyHostToDevice));
    CHECK_CUDA(cudaMemcpy(d_elen,  h_elen.data(),  sizeof(double) * h_elen.size(),  cudaMemcpyHostToDevice));

    const int warmup = 5;
    const int iters_grad = 50;
    const int iters_hess = 10;

    const float grad_ms = time_kernel_grad(d_x, d_tinit, d_elen, bendStiff, eps, d_g, N, warmup, iters_grad);
    const float hess_ms = time_kernel_hess(d_x, d_tinit, d_elen, bendStiff, eps, d_H, N, warmup, iters_hess);

    printf("N = %d\n", N);
    printf("grad kernel: %.6f ms/call  (%.3f ns/instance)\n", grad_ms, (grad_ms * 1e6) / N);
    printf("hess kernel: %.6f ms/call  (%.3f ns/instance)\n", hess_ms, (hess_ms * 1e6) / N);

    cudaFree(d_x); cudaFree(d_tinit); cudaFree(d_elen);
    cudaFree(d_g); cudaFree(d_H);
    return 0;
}
""")
