# sympy_codegen_neo_hookean_cuda_separate.py
# ------------------------------------------------------------
# Generates a CUDA .cu file that:
#   1) Computes GRADIENT only (g: 12 doubles) in kernel_grad
#   2) Computes HESSIAN only  (H: 12x12 doubles) in kernel_hess
#   3) Launches each kernel over N instances in parallel
#   4) Times each kernel with CUDA events (ms + per-instance ns)
#
# Model:
#   x:  12 DOFs (4 vertices * 3 coords), per instance
#   IB: 3x3 rest inverse (precomputed, constant), per instance
#   vol: rest volume (precomputed, constant), per instance
#
# Usage:
#   python sympy_codegen_neo_hookean_cuda_separate.py > neo_hookean_separate.cu
#
# Compile:
#   nvcc -O3 -std=c++17 -arch=sm_86 neo_hookean_separate.cu -o neo_hookean_separate
#
# Run:
#   ./neo_hookean_separate
#
# Notes:
# - Full Hessian storage is big: 144 doubles/instance.
# - This generator uses SymPy CSE separately for grad and Hessian
#   (kernels are independent, as requested).
# ------------------------------------------------------------

import sympy as sp
from sympy.printing.c import C99CodePrinter

printer = C99CodePrinter()

# ----------------------------
# Symbols
# ----------------------------
x = sp.Matrix(sp.symbols("x0:12", real=True))

ib00, ib01, ib02 = sp.symbols("ib00 ib01 ib02", real=True)
ib10, ib11, ib12 = sp.symbols("ib10 ib11 ib12", real=True)
ib20, ib21, ib22 = sp.symbols("ib20 ib21 ib22", real=True)
IB = sp.Matrix([[ib00, ib01, ib02],
                [ib10, ib11, ib12],
                [ib20, ib21, ib22]])

vol = sp.Symbol("vol", real=True)
mu  = sp.Symbol("mu", real=True)
lam = sp.Symbol("lam", real=True)

# ----------------------------
# Unpack x into 4 vertices
# ----------------------------
y0 = sp.Matrix([x[0],  x[1],  x[2]])
y1 = sp.Matrix([x[3],  x[4],  x[5]])
y2 = sp.Matrix([x[6],  x[7],  x[8]])
y3 = sp.Matrix([x[9],  x[10], x[11]])

Y0 = y1 - y0
Y1 = y2 - y0
Y2 = y3 - y0

# F columns are Y0,Y1,Y2
F  = sp.Matrix.hstack(Y0, Y1, Y2)     # (3,3)
FI = F * IB

# J  = FI.det()
J = sum(FI)
IC = sp.Add(*[FI[i, j] ** 2 for i in range(3) for j in range(3)])
I3 = IC + 1.0

shift = 1.0 + 0.75 * (mu / lam)

E = vol * (
    0.5 * mu * (IC - 3.0)
    - 0.5 * mu * sp.log(I3)
    + 0.5 * lam * (J - shift) ** 2
)

g = sp.Matrix([sp.diff(E, xi) for xi in x])   # (12,1)
H = g.jacobian(x)                              # (12,12)

# ----------------------------
# CSE separately for grad and Hessian
# ----------------------------
g_repls, g_red = sp.cse(list(g), optimizations="basic")
H_repls, H_red = sp.cse(list(H), optimizations="basic")  # row-major flattened by list(H)

def cexpr(expr):
    return printer.doprint(expr)

def emit_assign(sym, expr, indent="    "):
    return f"{indent}const double {sym} = {cexpr(expr)};"

# ----------------------------
# Emit CUDA .cu
# ----------------------------
print(r"""// Auto-generated by sympy_codegen_neo_hookean_cuda_separate.py
#include <cuda_runtime.h>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <vector>

#ifndef CHECK_CUDA
#define CHECK_CUDA(call) do {                                 \
  cudaError_t err = call;                                     \
  if (err != cudaSuccess) {                                   \
    fprintf(stderr, "CUDA error %s:%d: %s\n",                 \
            __FILE__, __LINE__, cudaGetErrorString(err));     \
    std::exit(1);                                             \
  }                                                           \
} while(0)
#endif

// Layout assumptions:
// x_in:   N * 12 doubles (row-major): x_in[i*12 + k]
// IB_in:  N * 9 doubles  (row-major): IB_in[i*9 + r*3 + c]
// vol_in: N doubles
// g_out:  N * 12 doubles
// H_out:  N * 144 doubles (row-major 12x12): H_out[i*144 + r*12 + c]
""")

# ----------------------------
# Gradient kernel
# ----------------------------
print(r"""
__global__ void neo_hookean_grad_kernel(
    const double* __restrict__ x_in,
    const double* __restrict__ IB_in,
    const double* __restrict__ vol_in,
    double mu, double lam,
    double* __restrict__ g_out,
    int N)
{
    const int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= N) return;

    // Load x
    const double x0  = x_in[i*12 + 0];
    const double x1  = x_in[i*12 + 1];
    const double x2  = x_in[i*12 + 2];
    const double x3  = x_in[i*12 + 3];
    const double x4  = x_in[i*12 + 4];
    const double x5  = x_in[i*12 + 5];
    const double x6  = x_in[i*12 + 6];
    const double x7  = x_in[i*12 + 7];
    const double x8  = x_in[i*12 + 8];
    const double x9  = x_in[i*12 + 9];
    const double x10 = x_in[i*12 + 10];
    const double x11 = x_in[i*12 + 11];

    // Load IB (row-major)
    const double ib00 = IB_in[i*9 + 0];
    const double ib01 = IB_in[i*9 + 1];
    const double ib02 = IB_in[i*9 + 2];
    const double ib10 = IB_in[i*9 + 3];
    const double ib11 = IB_in[i*9 + 4];
    const double ib12 = IB_in[i*9 + 5];
    const double ib20 = IB_in[i*9 + 6];
    const double ib21 = IB_in[i*9 + 7];
    const double ib22 = IB_in[i*9 + 8];

    const double vol = vol_in[i];

    // ---- common subexpressions (grad) ----
""")
for sym, expr in g_repls:
    print(emit_assign(str(sym), expr))

print(r"""
    // ---- write gradient ----
""")
for k in range(12):
    print(f"    g_out[i*12 + {k}] = {cexpr(g_red[k])};")

print("}\n")

# ----------------------------
# Hessian kernel
# ----------------------------
print(r"""
__global__ void neo_hookean_hess_kernel(
    const double* __restrict__ x_in,
    const double* __restrict__ IB_in,
    const double* __restrict__ vol_in,
    double mu, double lam,
    double* __restrict__ H_out,
    int N)
{
    const int i = blockIdx.x * blockDim.x + threadIdx.x;
    if (i >= N) return;

    // Load x
    const double x0  = x_in[i*12 + 0];
    const double x1  = x_in[i*12 + 1];
    const double x2  = x_in[i*12 + 2];
    const double x3  = x_in[i*12 + 3];
    const double x4  = x_in[i*12 + 4];
    const double x5  = x_in[i*12 + 5];
    const double x6  = x_in[i*12 + 6];
    const double x7  = x_in[i*12 + 7];
    const double x8  = x_in[i*12 + 8];
    const double x9  = x_in[i*12 + 9];
    const double x10 = x_in[i*12 + 10];
    const double x11 = x_in[i*12 + 11];

    // Load IB (row-major)
    const double ib00 = IB_in[i*9 + 0];
    const double ib01 = IB_in[i*9 + 1];
    const double ib02 = IB_in[i*9 + 2];
    const double ib10 = IB_in[i*9 + 3];
    const double ib11 = IB_in[i*9 + 4];
    const double ib12 = IB_in[i*9 + 5];
    const double ib20 = IB_in[i*9 + 6];
    const double ib21 = IB_in[i*9 + 7];
    const double ib22 = IB_in[i*9 + 8];

    const double vol = vol_in[i];

    // ---- common subexpressions (hess) ----
""")
for sym, expr in H_repls:
    print(emit_assign(str(sym), expr))

print(r"""
    // ---- write Hessian (row-major 12x12) ----
""")
# H_red is list of 144 expressions in row-major because list(H) iterates rows then cols in SymPy Matrix
for idx in range(144):
    print(f"    H_out[i*144 + {idx}] = {cexpr(H_red[idx])};")

print("}\n")

# ----------------------------
# Timing main
# ----------------------------
print(r"""
static float time_kernel_grad(
    const double* d_x, const double* d_IB, const double* d_vol,
    double mu, double lam,
    double* d_g, int N, int warmup, int iters)
{
    const int threads = 256;
    const int blocks = (N + threads - 1) / threads;

    // Warmup
    for (int k = 0; k < warmup; ++k) {
        neo_hookean_grad_kernel<<<blocks, threads>>>(d_x, d_IB, d_vol, mu, lam, d_g, N);
    }
    CHECK_CUDA(cudaGetLastError());
    CHECK_CUDA(cudaDeviceSynchronize());

    cudaEvent_t start, stop;
    CHECK_CUDA(cudaEventCreate(&start));
    CHECK_CUDA(cudaEventCreate(&stop));
    CHECK_CUDA(cudaEventRecord(start));

    for (int k = 0; k < iters; ++k) {
        neo_hookean_grad_kernel<<<blocks, threads>>>(d_x, d_IB, d_vol, mu, lam, d_g, N);
    }

    CHECK_CUDA(cudaEventRecord(stop));
    CHECK_CUDA(cudaEventSynchronize(stop));

    float ms = 0.0f;
    CHECK_CUDA(cudaEventElapsedTime(&ms, start, stop));
    CHECK_CUDA(cudaEventDestroy(start));
    CHECK_CUDA(cudaEventDestroy(stop));

    return ms / iters;
}

static float time_kernel_hess(
    const double* d_x, const double* d_IB, const double* d_vol,
    double mu, double lam,
    double* d_H, int N, int warmup, int iters)
{
    const int threads = 256;
    const int blocks = (N + threads - 1) / threads;

    // Warmup
    for (int k = 0; k < warmup; ++k) {
        neo_hookean_hess_kernel<<<blocks, threads>>>(d_x, d_IB, d_vol, mu, lam, d_H, N);
    }
    CHECK_CUDA(cudaGetLastError());
    CHECK_CUDA(cudaDeviceSynchronize());

    cudaEvent_t start, stop;
    CHECK_CUDA(cudaEventCreate(&start));
    CHECK_CUDA(cudaEventCreate(&stop));
    CHECK_CUDA(cudaEventRecord(start));

    for (int k = 0; k < iters; ++k) {
        neo_hookean_hess_kernel<<<blocks, threads>>>(d_x, d_IB, d_vol, mu, lam, d_H, N);
    }

    CHECK_CUDA(cudaEventRecord(stop));
    CHECK_CUDA(cudaEventSynchronize(stop));

    float ms = 0.0f;
    CHECK_CUDA(cudaEventElapsedTime(&ms, start, stop));
    CHECK_CUDA(cudaEventDestroy(start));
    CHECK_CUDA(cudaEventDestroy(stop));

    return ms / iters;
}

int main() {
    // Demo N (change as needed)
    const int N = 79935;  // 32768
    const double mu = 2000.0;
    const double lam = 1000.0;

    // Host buffers (dummy init)
    std::vector<double> h_x(N * 12, 0.0);
    std::vector<double> h_IB(N * 9, 0.0);
    std::vector<double> h_vol(N, 1.0);

    for (int i = 0; i < N; ++i) {
        for (int k = 0; k < 12; ++k) h_x[i*12 + k] = 0.01 * (k + 1);
        // Identity IB
        h_IB[i*9 + 0] = 1.0; h_IB[i*9 + 4] = 1.0; h_IB[i*9 + 8] = 1.0;
        h_vol[i] = 1.0;
    }

    // Device buffers
    double *d_x=nullptr, *d_IB=nullptr, *d_vol=nullptr, *d_g=nullptr, *d_H=nullptr;
    CHECK_CUDA(cudaMalloc(&d_x,   sizeof(double) * h_x.size()));
    CHECK_CUDA(cudaMalloc(&d_IB,  sizeof(double) * h_IB.size()));
    CHECK_CUDA(cudaMalloc(&d_vol, sizeof(double) * h_vol.size()));
    CHECK_CUDA(cudaMalloc(&d_g,   sizeof(double) * N * 12));
    CHECK_CUDA(cudaMalloc(&d_H,   sizeof(double) * N * 144));

    CHECK_CUDA(cudaMemcpy(d_x,   h_x.data(),   sizeof(double) * h_x.size(),   cudaMemcpyHostToDevice));
    CHECK_CUDA(cudaMemcpy(d_IB,  h_IB.data(),  sizeof(double) * h_IB.size(),  cudaMemcpyHostToDevice));
    CHECK_CUDA(cudaMemcpy(d_vol, h_vol.data(), sizeof(double) * h_vol.size(), cudaMemcpyHostToDevice));

    const int warmup = 5;
    const int iters_grad = 50;
    const int iters_hess = 20;

    const float grad_ms = time_kernel_grad(d_x, d_IB, d_vol, mu, lam, d_g, N, warmup, iters_grad);
    const float hess_ms = time_kernel_hess(d_x, d_IB, d_vol, mu, lam, d_H, N, warmup, iters_hess);

    printf("N = %d\n", N);
    printf("grad kernel: %.6f ms/call  (%.3f ns/instance)\n", grad_ms, (grad_ms * 1e6) / N);
    printf("hess kernel: %.6f ms/call  (%.3f ns/instance)\n", hess_ms, (hess_ms * 1e6) / N);

    // Cleanup
    cudaFree(d_x); cudaFree(d_IB); cudaFree(d_vol);
    cudaFree(d_g); cudaFree(d_H);
    return 0;
}
""")
