from __future__ import annotations
from yasps.attribute import attribute
from typing import List, Tuple, Dict
import pycuda.gpuarray as gpuarray
import ctypes
import numpy as np
from yasps.attribute import JOIN, DATA, UNION
from yasps.helper import timed
import os
import pycuda.driver as cuda
from yasps.helper import prune_duplicate_functions

########################################################################
# The gradient indices kernel has multiple functions
# 1. Getting all the indices of the attributes that are used for every local instance
# 2. Compress it locally to avoid too large of the local hessian
#    this compression will also give us couple arrays that tells us
#    the number of unique hessian sizes
#    for each unique hessian size, which instances has that size
#    the outer index(just to know where to begin and end)
# 3. We will also check the number of coordinates used for each instance
#    since we compressed the hessian, it is possible that originally there are
#    5 indices, and after compression there are 3 indices
#    after expansion, it means there are 3 * 4 / 2 = 6 coordinates
#    we will the need to know, for each instance, the number of unique coordinates locally
#    we do this by again having an outer index, this way we not only know where the coordinate starts
#    we also know how many there are
# 4. finally, the coordinates, those coordinates are allowed to have duplicates
#    the deduplication will be left to the minimizer
# 5. additionally, the dimension of those coordinates (block width and height)
compression_kernel_string = '''
#include <thrust/device_vector.h>
#include <thrust/sort.h>
#include <thrust/unique.h>
#include <thrust/copy.h>
#include <thrust/scan.h>
#include <thrust/transform.h>
#include <thrust/iterator/counting_iterator.h>
#include <cuda_runtime.h>
#include <vector>
// for checking cuda error
#define CUDA_CHECK_ERROR(ans)                                                  \
  {{ cudaAssert((ans), __FILE__, __LINE__); }}
inline void cudaAssert(cudaError_t code, const char *file, int line,
                        bool abort = true) {{
                        if (code != cudaSuccess) {{
    fprintf(stderr, "CUDA Error: %s at %s:%d\\n", cudaGetErrorString(code), file,
            line);
    if (abort)
      exit(code);
  }}
}}

__global__ void computePermutation(
    const unsigned int* indices,           // the index we use to put back the gradient
    const unsigned short int* index_sizes, // the size of the attribute corresponding to this index
    short int* permutation,                // how do we locally permute it
    unsigned short int* total_gradient_sizes, // the total size of the gradient generated by this instance
    unsigned int* compressed_index_sizes,     // the total number of indices needed after the compression
    unsigned int N,                           // maximum number of instances
    unsigned int K                            // maximum number of indices
  ) {
  unsigned int tid = blockIdx.x * blockDim.x + threadIdx.x;
  if (tid < N) {
    int gradient_offset = 0;
    unsigned short int total_gradient_size = 0;
    unsigned int compressed_index_size = 0;
    total_gradient_sizes[tid] = 0;
    compressed_index_sizes[tid] = 0;
    for (unsigned short int i = 0; i < K; ++i) {
      // first we check if the index already exists in this local array
      const unsigned int idx_i = indices[tid * K + i];
      if (idx_i == 0){
        // we hit an empty index, this is a reserved space for the union operation
        // we continue
        continue;
      }
      bool found = false;
      for (unsigned short int j = 0; j < i; j++){
        const unsigned int idx_j = indices[tid * K + j];
        if (idx_j == idx_i) {
          // we found a duplicate
          permutation[tid * K + i] = -permutation[tid * K + j];
          found = true;
          break;
        }
      }
      if (!found) {
        permutation[tid * K + i] = gradient_offset + 1; // always exclude 0
        gradient_offset += index_sizes[tid * K + i]; // we offset the gradient_offset so we know exactly where to put this segment
        total_gradient_size += index_sizes[tid * K + i];
        compressed_index_size++;
      }
    }
    total_gradient_sizes[tid] = total_gradient_size; // record after compression, the size of the gradient
    compressed_index_sizes[tid] = compressed_index_size; // the number of unique indices in this instance
  }
}
// Functor to apply the transformation x * (x + 1) / 2
struct triangular_transform {
  __host__ __device__
  unsigned int operator()(const unsigned int& x) const {
    return x * (x + 1) / 2;
  }
};
extern "C" {
int compress_indices(
  const unsigned int* d_indices,           // indices for each local gradient
  const unsigned short int* d_index_sizes,       // sizes of each variable for each index
  short int* d_permutations,               // permutations for compression
  unsigned short int* d_total_gradient_sizes,    // total sizes per gradient
  unsigned int* d_compressed_coordinate_counts_ounter,  // the number of indices for gradient after compression
  unsigned short int* d_unique_sizes,            // unique gradient sizes
  unsigned int* d_grouped_indices,         // grouped indices by gradient size
  unsigned int* d_offsets,                 // offsets for compressed indices
  unsigned short int* d_num_unique,              // number of unique sizes
  unsigned int num_instances,
  unsigned int num_indices_for_each_instance
) {
  // Compute permutation and total sizes
  computePermutation<<<(num_instances + 256 - 1) / 256, 256>>>(
    d_indices,
    d_index_sizes,
    d_permutations,
    d_total_gradient_sizes,
    d_compressed_coordinate_counts_ounter + 1,
    num_instances,
    num_indices_for_each_instance
  );
  // Wrap existing memory (no extra allocation)
  auto total_sizes_begin = thrust::device_pointer_cast(d_total_gradient_sizes);
  auto total_sizes_end   = total_sizes_begin + num_instances;
  auto grouped_indices_begin = thrust::device_pointer_cast(d_grouped_indices);

  // Initialize d_grouped_indices as [0, 1, 2, ..., num_instances-1]
  thrust::sequence(grouped_indices_begin, grouped_indices_begin + num_instances);

  // Sort total_gradient_sizes and reorder grouped_indices accordingly
  thrust::sort_by_key(
    total_sizes_begin, total_sizes_end, grouped_indices_begin
  );

  // Compute flags marking unique starts (no extra alloc for sorted_values)
  thrust::device_vector<unsigned int> flags(num_instances);
  flags[0] = 1;
  thrust::transform(
    total_sizes_begin + 1, total_sizes_end,
    total_sizes_begin,
    flags.begin() + 1,
    thrust::not_equal_to<unsigned int>()
  );
  // Get the unique count directly
  unsigned short int unique_count = thrust::count(flags.begin(), flags.end(), 1u);
  cudaMemcpy(d_num_unique, &unique_count, sizeof(unsigned short int), cudaMemcpyHostToDevice);

  // Compute offsets directly into provided memory (no extra alloc)
  thrust::copy_if(
    thrust::make_counting_iterator(0),
    thrust::make_counting_iterator((int)num_instances),
    flags.begin(),
    thrust::device_pointer_cast(d_offsets),
    thrust::identity<unsigned int>()
  );
  // Set the last offset to num_instances explicitly
  cudaMemcpy(d_offsets + unique_count, &num_instances, sizeof(unsigned int), cudaMemcpyHostToDevice);
  // Copy unique sizes directly into provided memory
  thrust::copy_if(
    total_sizes_begin, total_sizes_end,
    flags.begin(),
    thrust::device_pointer_cast(d_unique_sizes),
    thrust::identity<unsigned int>()
  );
  CUDA_CHECK_ERROR(cudaDeviceSynchronize());
  // now we count for the energy, the number of coordinates we need to allocate
  thrust::device_ptr<unsigned int> count_ptr(d_compressed_coordinate_counts_ounter);
  thrust::transform(
    count_ptr + 1,                 // input start
    count_ptr + 1 + num_instances, // input end
    count_ptr + 1,                 // output start
    triangular_transform()         // transformation
  );
  // Compute prefix sum (exclusive) on transformed values, store back
  // this way, we know where the coordinate starts and ends
  thrust::inclusive_scan(
    count_ptr + 1,                 // input start
    count_ptr + 1 + num_instances, // input end
    count_ptr + 1                  // output: starts at index 0
  );
  cudaError_t err = cudaDeviceSynchronize();
  if (err != cudaSuccess) {
    fprintf(stderr, "CUDA Error (synchronize): %s\\n", cudaGetErrorString(err));
    return -1;
  }
  return 0;
}
} // extern "C"
'''

coordinate_kernel_string = '''
#include <stdio.h>
#include <stdlib.h>
#include <cuda_runtime.h>
// for checking cuda error
#define CUDA_CHECK_ERROR(ans)                                                  \
  {{ cudaAssert((ans), __FILE__, __LINE__); }}
inline void cudaAssert(cudaError_t code, const char *file, int line,
                        bool abort = true) {{
                        if (code != cudaSuccess) {{
    fprintf(stderr, "CUDA Error: %s at %s:%d\\n", cudaGetErrorString(code), file,
            line);
    if (abort)
      exit(code);
  }}
}}
__device__ void computeCoordinatesDeviceFunction(const unsigned int* indices,
                                   const short int* permutations,
                                   const short unsigned int* indexSizes,
                                   unsigned int* coordinates,
                                   unsigned short int* dimensions,
                                   const unsigned int num_indices_for_each_instance){
  unsigned int total_coordinates = 0;
  for (unsigned int i = 0; i < num_indices_for_each_instance; i++) {
    const unsigned int ind_i = indices[i];
    const int permutation_i = permutations[i];
    if (permutation_i > 0){
      for (unsigned int j = i; j < num_indices_for_each_instance; j++){
        const unsigned int ind_j = indices[j];
        const int permutation_j = permutations[j];
        if (permutation_j > 0){
          // this is a valid coordinate that is not compressed
          // we also only want the upper triangular part
          if (ind_i < ind_j){
            coordinates[total_coordinates] = ind_i - 1;
            coordinates[total_coordinates + 1] = ind_j - 1;
            dimensions[total_coordinates] = indexSizes[i];
            dimensions[total_coordinates + 1] = indexSizes[j];
          }else{
            coordinates[total_coordinates] = ind_j - 1;
            coordinates[total_coordinates + 1] = ind_i - 1;
            dimensions[total_coordinates] = indexSizes[j];
            dimensions[total_coordinates + 1] = indexSizes[i];
          }
          total_coordinates += 2;
        }
      }
    }
  }
}

__global__ void computeCoordinatesGlobalFunction(const unsigned int* indices, // the index, or coordinate
                                                 const short int* permutations,     // how we permute the indices to compress them
                                                 const short unsigned int* indexSizes, // the size for each index (the size of the corresponding attribute)
                                                 unsigned int* coordinates, // output the coordinates
                                                 unsigned short int* dimensions, // output the dimensions
                                                 const unsigned int* coordinatesCountsOuterIndices, // this will tell us, how many coordinates are we expecting for each instance, and where the begin of it should be
                                                 const unsigned int num_indices_for_each_instance, // how many indices are we expecting for each instance
                                                 const unsigned int num_instances // how many instances
                                                ){

  unsigned int tid = blockIdx.x * blockDim.x + threadIdx.x;
  if (tid < num_instances) {
    const unsigned int coordinateStart = coordinatesCountsOuterIndices[tid] * 2;
    computeCoordinatesDeviceFunction(indices + tid * num_indices_for_each_instance,
                                     permutations + tid * num_indices_for_each_instance,
                                     indexSizes + tid * num_indices_for_each_instance,
                                     coordinates + coordinateStart,
                                     dimensions + coordinateStart,
                                     num_indices_for_each_instance);
  }
}


extern "C"
{
int computeCoordinates(
  const unsigned int* indices, // the index, or coordinate
  const short int* permutations,     // how we permute the indices to compress them
  const short unsigned int* indexSizes, // the size for each index (the size of the corresponding attribute)
  unsigned int* coordinates, // output the coordinates
  unsigned short int* dimensions, // output the dimensions
  const unsigned int* coordinatesCountsOuterIndices, // this will tell us, how many coordinates are we expecting for each instance, and where the begin of it should be
  const unsigned int num_indices_for_each_instance, // how many indices are we expecting for each instance
  const unsigned int num_instances // how many instances
){
  computeCoordinatesGlobalFunction<<<(num_instances + 255) / 256, 256>>>(indices, permutations, indexSizes, coordinates, dimensions, coordinatesCountsOuterIndices, num_indices_for_each_instance, num_instances);
  cudaError_t err = cudaDeviceSynchronize();
  if (err != cudaSuccess) {
    fprintf(stderr, "CUDA Error (synchronize): %s\\n", cudaGetErrorString(err));
    return -1;
  }
  return 0;
}
}'''

# The gradient indices kernel needs to produce couple of things:
# The most obvious one is globally, how to map each block to the global matrix
# The not so obvious one is locally, within this local hessian, how can I compress iter
# The compression is used so that when variables are dependent on each other
# we can reduce the size of the hessian
# The third thing is just the size of the compressed hessian
# so that we can pre allocate a kernel for that specific hessian size (for projection)
# The first three things should have same dimension, as in the output array have the same size
class gradientIndicesKernel:
  @timed("gradientIndicesKernel.__init__")
  def __init__(self, path_dict: Dict[attribute, List[attribute]], unioned_child_to_its_children: Dict[attribute, List[attribute]], wrt: List[attribute], wrt_start_indices: List[int], energy: attribute):
    self.__path_dict: Dict[attribute, List[attribute]] = path_dict # the path dict is basically from parent to children
    self.__unioned_child_to_its_children: Dict[attribute, List[attribute]] = unioned_child_to_its_children # this is the unioned child to its children
    # print("Checking unioned child to its children")
    # for key in self.__unioned_child_to_its_children:
    #   print(f"Unioned child: {key.fullName}, children: {[x.fullName for x in self.__unioned_child_to_its_children[key]]}")
    self.__wrt_start_indices: List[int] = wrt_start_indices
    self.__energy: attribute = energy
    self.__used_join_attributes: List[attribute] = [] # all the join attributes, we will use its connectivities for indexing
    self.__used_union_attributes: List[attribute] = [] # all the union attributes, we will them for indexing
    self.__gradientSizeForEachPart: Dict[attribute, int] = {} # determine for each attribute, the size of the gradient being used, this will always record the theoretical largest size of the gradient (the size before compression)
    self.__indexSizeForEachPart: Dict[attribute, int] = {} # determine for each attribute, the number of indices needed, again this is the theoretical largest size
    self.__getUsedJoinAttributes() # get the attributes that are join operations, so we can just grab the connectivities later on
    self.__getUsedUnionAttributes() # get the attributes that are union operationsn
    self.__wrt: List[attribute] = wrt # the wrt attributes, we will use this to determine the position in the wrt start indices
    self.__gradientSize, self.__indexSize = self.__getGradientSize(self.__path_dict, self.__energy)
    # print("Index size and gradient size for each part check")
    # for item in self.__indexSizeForEachPart:
    #   print(f"Name: {item.fullName}, index size: {self.__indexSizeForEachPart[item]}, gradient size: {self.__gradientSizeForEachPart[item]}")

    # exit(0)

    self.__positionInWrtStartIndices: Dict[attribute, int] = {} # we record the position in the wrt start indices
    for i in range(len(wrt)):
      self.__positionInWrtStartIndices[wrt[i]] = i # we honestly only care about its index, not the starting position, because the wrt should not change, but the starting positions might
    self.__kernelString = ""
    self.__numInstances: int = 0 # for checking the number of instances
    self.__maxInstances: int = 0 # for allocating the largest gpu array
    # the output data
    ####################################################
    # Here are the uncompressed output indices
    ####################################################
    self.__outputIndices: gpuarray.GPUArray = gpuarray.empty(0, dtype=np.uint32) # this will record the raw indices for each energy term wrt the attributes used
    self.__outputIndexSizes: gpuarray.GPUArray = gpuarray.empty(0, dtype=np.uint16) # for each index, the attribute dimension is recorded in this array
    ####################################################
    # Here are information needed for compressed indices
    # for any array that record sizes, it can be uint16
    # for any array related to indices, it should be uint32
    ####################################################
    self.__outputPermutations: gpuarray.GPUArray = gpuarray.empty(0, dtype=np.int16) # this will record how to compress the matrix locally
    self.__outputGradientSizes: gpuarray.GPUArray = gpuarray.empty(0, dtype=np.uint16) # this will record the total size of gradient after compression
    self.__outputUniqueGradientSizes: gpuarray.GPUArray = gpuarray.empty(0, dtype=np.uint16) # this will record the unique sizes of the gradients after compression
    self.__outputUniqueGradientSizesCPU = None
    self.__outputGroupedIndicesInner: gpuarray.GPUArray = gpuarray.empty(0, dtype=np.uint32) # this will record the grouped indices by the compressed gradient size
    self.__outputGroupedIndicesOuter: gpuarray.GPUArray = gpuarray.empty(0, dtype=np.uint32) # this will record the offsets used to find the starting and ending points of the grouped indices
    self.__outputNumUniqueGradientSizes: gpuarray.GPUArray = gpuarray.empty(0, dtype=np.uint16) # this will record the number of unique sizes of the gradients after compression
    self.__outputNumUniqueGradientSizesCPU = None
    self.__outputCompressedCoordinateCountsOuter: gpuarray.GPUArray = gpuarray.empty(0, dtype=np.uint32) # for recording how many indices are in the compressed gradient
    ####################################################
    # Here are information needed for coordinate generation
    # we will have 1 array of uint32 which stores the uncompressed coordinates
    # and another array of uint16 which stores the dimension of the blocks
    self.__outputCoordinates: gpuarray.GPUArray = gpuarray.empty(0, dtype=np.uint32) # this will record the uncompressed coordinates
    self.__outputBlockDimensions: gpuarray.GPUArray = gpuarray.empty(0, dtype=np.uint16) # this will record the dimension of the blocks
    ####################################################

    ####################################################
    # Here are the kernels
    ####################################################
    self.__indices_kernel = None # the kernel for computing the indices
    self.__compression_kernel = None # the kernel for compressing the indices
    self.__coordinate_kernel = None # the kernel for compressing the indices
    self.__generateKernel() # generate and compile the kernel
    self.__getCompressionKernel() # generate or just get the compression kernel
    self.__getCoordinateKernel() # generate or just get the coordinate kernel

    # we can pre allocate the spaces for unique sizes
    self.__outputUniqueGradientSizes = gpuarray.empty(self.__gradientSizeForEachPart[energy] + 1, np.uint16) # this is the largest possible size
    self.__outputGroupedIndicesOuter = gpuarray.empty(self.__gradientSizeForEachPart[energy] + 2, np.uint32) # this will record the offsets used to find the starting and ending points of the grouped indices
    self.__outputNumUniqueGradientSizes = gpuarray.empty(1, np.uint16) # this will record the number of unique sizes of the attributes after compression


  @property
  def maxNumIndicesNeeded(self):
    return self.__indexSizeForEachPart[self.__energy] # return how many indices are needed for each instance of the energy, used for allocation

  @property
  def outputIndices(self):
    return self.__outputIndices

  @property
  def outputSizes(self):
    return self.__outputIndexSizes

  @property
  def outputCoordinates(self):
    return self.__outputCoordinates

  @property
  def outputBlockDimensions(self):
    return self.__outputBlockDimensions

  @property
  def outputUniqueGradientSizes(self):
    return self.__outputUniqueGradientSizes

  @property
  def outputGroupedIndicesInner(self):
    return self.__outputGroupedIndicesInner

  @property
  def outputGroupedIndicesOuter(self):
    return self.__outputGroupedIndicesOuter

  @property
  def numUniqueGradientSizes(self):
    if self.__numInstances == 0:
      return 0
    return self.__outputNumUniqueGradientSizes.get()[0]

  @property
  def numUniqueGradientSizesCPU(self):
    if self.__numInstances == 0:
      return 0
    # if self.__outputNumUniqueGradientSizesCPU is None:
    self.__outputNumUniqueGradientSizesCPU = self.__outputNumUniqueGradientSizes.get()[0]
    return self.__outputNumUniqueGradientSizesCPU

  @property
  def outputUniqueGradientSizesCPU(self):
    if self.__numInstances == 0:
      return np.array([], dtype=np.uint16)
    # if self.__outputUniqueGradientSizesCPU is None:
    self.__outputUniqueGradientSizesCPU = np.array(self.__outputUniqueGradientSizes.get(), dtype=np.uint16).flatten()[:self.numUniqueGradientSizesCPU]
    return self.__outputUniqueGradientSizesCPU

  @property
  def outputPermutations(self):
    return self.__outputPermutations

  @property
  def outputCompressedCoordinateCountsOuter(self):
    return self.__outputCompressedCoordinateCountsOuter


  def __getCompressionKernel(self):
    if self.__compression_kernel is None:
      file_name = ".yasps_constant/compression_kernel"
      # check if the file exists
      if not os.path.exists(f'{file_name}.so'):
        # generate the kernel
        f = open(f"{file_name}.cu", 'w')
        f.write(compression_kernel_string)
        f.close()
        os.system(f"nvcc -Xcompiler -fPIC -shared -o {file_name}.so {file_name}.cu -O3 -arch=sm_86 -lcudart -lcuda")
        self.__compression_kernel = ctypes.CDLL(f"{file_name}.so").compress_indices # get the compiled kernel
        self.__compression_kernel.restype = ctypes.c_int # set the return type to None
        self.__compression_kernel.argtypes = [ctypes.c_void_p] * 9 + [ctypes.c_uint32] * 2
      else:
        self.__compression_kernel = ctypes.CDLL(f"{file_name}.so").compress_indices # get the compiled kernel
        self.__compression_kernel.restype = ctypes.c_int # set the return type to None
        self.__compression_kernel.argtypes = [ctypes.c_void_p] * 9 + [ctypes.c_uint32] * 2

  def __getCoordinateKernel(self):
    if self.__coordinate_kernel is None:
      file_name = ".yasps_constant/coordinate_kernel"
      # check if the file exists
      if not os.path.exists(f'{file_name}.so'):
        # generate the kernel
        f = open(f"{file_name}.cu", 'w')
        f.write(coordinate_kernel_string)
        f.close()
        os.system(f"nvcc -Xcompiler -fPIC -shared -o {file_name}.so {file_name}.cu -O3 -arch=sm_86 -lcudart -lcuda")
        self.__coordinate_kernel = ctypes.CDLL(f"{file_name}.so").computeCoordinates # get the compiled kernel
        self.__coordinate_kernel.restype = ctypes.c_int # set the return type to None
        self.__coordinate_kernel.argtypes = [ctypes.c_void_p] * 6 + [ctypes.c_uint32] * 2
      else:
        self.__coordinate_kernel = ctypes.CDLL(f"{file_name}.so").computeCoordinates # get the compiled kernel
        self.__coordinate_kernel.restype = ctypes.c_int # set the return type to None
        self.__coordinate_kernel.argtypes = [ctypes.c_void_p] * 6 + [ctypes.c_uint32] * 2

  def __to_void_p(self, x: gpuarray.GPUArray):
    if x is None or x.size == 0:
      # Return a NULL pointer if array is empty
      return ctypes.c_void_p(None)
    assert x.gpudata is not None
    return ctypes.c_void_p(int(x.gpudata))


  def __getGradientSize(self, path_dict: Dict[attribute, List[attribute]], current_attribute: attribute) -> Tuple[int, int]:
    # we first get the list of attributes to look for
    if current_attribute in self.__gradientSizeForEachPart:
      return self.__gradientSizeForEachPart[current_attribute], self.__indexSizeForEachPart[current_attribute] # if we already computed the size, just return it

    total_size = 0
    index_size = 0
    # we need to do special case for JOIN and UNION
    # for union operator, we always know that the size is the maximum size of the children
    # and for join operator, we simply duplicate the size
    if current_attribute.operator == JOIN:
      # we first get the size of its children
      for child in path_dict[current_attribute]:
        child_gradient_size, child_index_size = self.__getGradientSize(path_dict, child)
        total_size += child_gradient_size * current_attribute.through.dimension # we multiply by the dimension number
        index_size += child_index_size * current_attribute.through.dimension # we multiply by the dimension number
      self.__gradientSizeForEachPart[current_attribute] = total_size # also record that for each join operation, the size we need to reserve
      self.__indexSizeForEachPart[current_attribute] = index_size # also record that for each join operation, the size we need to reserve
      return total_size, index_size
    if current_attribute.operator == UNION:
      # we check for each child, the size
      # and then take the max
      for child in current_attribute.children:
        child_gradient_size, child_index_size = self.__getGradientSize(path_dict, child)
        total_size = max(child_gradient_size, total_size)
        index_size = max(child_index_size, index_size)
      self.__gradientSizeForEachPart[current_attribute] = total_size
      self.__indexSizeForEachPart[current_attribute] = index_size
      return total_size, index_size
    if current_attribute.operator == DATA:
      self.__gradientSizeForEachPart[current_attribute] = current_attribute.size # the gradient size for the data attribute is its own size
      self.__indexSizeForEachPart[current_attribute] = 1 # the index size for the data attribute is 1
      return current_attribute.size, 1 # the size is just the size of the data attribute and the index size is 1

    children_attributes: List[attribute] = []
    if current_attribute in path_dict:
      children_attributes = path_dict[current_attribute] # get the children attributes from the path dict, this is a node on the path
    elif current_attribute in self.__unioned_child_to_its_children:
      unioned_children = self.__unioned_child_to_its_children[current_attribute]
      for child in unioned_children:
        if child in path_dict or child in self.__wrt:
          # if the child is in the path dict, we can use it
          children_attributes.append(child)
    else:
      raise ValueError(f"Attribute {current_attribute.fullName} is not in the path dict or unioned child to its children, cannot compute gradient size.")

    # now we have all the children, we accumulate the size
    for child in children_attributes:
      child_gradient_size, child_index_size = self.__getGradientSize(path_dict, child) # get the gradient size and index size for each child
      total_size += child_gradient_size # accumulate the gradient size
      index_size += child_index_size # accumulate the index size
    self.__gradientSizeForEachPart[current_attribute] = total_size # record the gradient size for each child
    self.__indexSizeForEachPart[current_attribute] = index_size # record the index size for each child
    return total_size, index_size # return the total size and index size

  def __getUsedJoinAttributes(self):
    # we literally just go over the attributes
    for att in self.__path_dict.keys():
      if att.operator == JOIN:
        self.__used_join_attributes.append(att)

  def __getUsedUnionAttributes(self):
    # we literally just go over the attributes
    for att in self.__path_dict.keys():
      if att.operator == UNION:
        self.__used_union_attributes.append(att)

  def __generateKernel(self):
    # ok now we compile the kernel by saving it to a file and then calling nvcc
    file_name = f".yasps_tmp/{self.__energy.fullName}_get_indices"
    if os.path.exists(f'{file_name}.so'):
      # we just use that file?
      self.__indices_kernel = ctypes.CDLL(f"{file_name}.so").get_indices # get the compiled kernel
      self.__indices_kernel.restype = ctypes.c_int # set the return type to None
      self.__indices_kernel.argtypes = [ctypes.c_void_p] * len(self.__used_join_attributes) + [ctypes.c_void_p] * len(self.__used_union_attributes) + [ctypes.c_void_p] * 3 + [ctypes.c_uint32]
      return


    # ok now we need to generate the kernel
    # what we basically aim to do
    # is to have an isolated kernel that calls the children kernel to fetch the data
    self.__kernelString += '''
#include <stdio.h>
#include <stdlib.h>
#include <cuda_runtime.h>
'''
    # now, for each parent-child relationship, we will have a kernel
    for parent in self.__path_dict.keys():
      for child in self.__path_dict[parent]:
        # now put a kernel function header
        self.__kernelString += f'''
__device__ inline void {parent.fullName}_get_indices_from_{child.fullName}(
  {", ".join([f"const unsigned int* {x.fullName}_indices" for x in self.__used_join_attributes]) + ", " if self.__used_join_attributes else ""}
  {", ".join([f"const unsigned int* {x.correspondance.code_generation_counts_name}" for x in self.__used_union_attributes]) + ", " if self.__used_union_attributes else ""}
  const unsigned int* wrtStartIndices,
  unsigned int* outputIndices,
  unsigned short int* outputSizes,
  unsigned int index
);
'''
      # we also add a header function that will be used to fetch the index for the entire parent and children
      self.__kernelString += f'''
__device__ inline void {parent.fullName}_get_indices(
  {", ".join([f"const unsigned int* {x.fullName}_indices" for x in self.__used_join_attributes]) + ", " if self.__used_join_attributes else ""}
  {", ".join([f"const unsigned int* {x.correspondance.code_generation_counts_name}" for x in self.__used_union_attributes]) + ", " if self.__used_union_attributes else ""}
  const unsigned int* wrtStartIndices,
  unsigned int* outputIndices,
  unsigned short int* outputSizes,
  unsigned int index
);
'''
    # ok we have produced the header functions, we will start the actual implementation
    for parent in self.__path_dict.keys():
      for (index, child) in enumerate(self.__path_dict[parent]):
        # we will now construct the actual function
        self.__kernelString += f'''
__device__ inline void {parent.fullName}_get_indices_from_{child.fullName}(
  {", ".join([f"const unsigned int* {x.fullName}_indices" for x in self.__used_join_attributes]) + ", " if self.__used_join_attributes else ""}
  {", ".join([f"const unsigned int* {x.correspondance.code_generation_counts_name}" for x in self.__used_union_attributes]) + ", " if self.__used_union_attributes else ""}
  const unsigned int* wrtStartIndices,
  unsigned int* outputIndices,
  unsigned short int* outputSizes,
  unsigned int index
){{'''
        if child.operator == DATA:
          # we have reached the bottom
          # we now record that index, added by offset, and the size of this attribute
          # we determine its position in wrt
          pos: int = self.__positionInWrtStartIndices[child]
          self.__kernelString += f'''
  // we add 1 so that we can use 0 as a flag for empty
  // the empty is used to indicate that we reserve space for union operator
  outputIndices[0] = wrtStartIndices[{pos}] + index * {child.size if child.correspondance.type == "primitive" else 0} + 1; // map the index to the index in final gradient array
  outputSizes[0] = {child.size}; // provide the size of this attribute for a single instance
'''
        elif child.operator == JOIN:
          # we are at a join operator again
          # we will need to get the children attributes
          self.__kernelString += f'''
  // we still need to keep going, go ahead and call the function that accumulates indices
  {child.fullName}_get_indices(
    {", ".join([f"{x.fullName}_indices" for x in self.__used_join_attributes]) + ", " if self.__used_join_attributes else ""}
    {", ".join([f"{x.correspondance.code_generation_counts_name}" for x in self.__used_union_attributes]) + ", " if self.__used_union_attributes else ""}
    wrtStartIndices,
    outputIndices,
    outputSizes,
    index
  );
'''
        elif child.operator == UNION:
          # at union operator, do the same thing
          self.__kernelString += f'''
  {child.fullName}_get_indices(
    {", ".join([f"{x.fullName}_indices" for x in self.__used_join_attributes]) + ", " if self.__used_join_attributes else ""}
    {", ".join([f"{x.correspondance.code_generation_counts_name}" for x in self.__used_union_attributes]) + ", " if self.__used_union_attributes else ""}
    wrtStartIndices,
    outputIndices,
    outputSizes,
    index
  );
'''
        self.__kernelString += f'''
}} // end of kernel for grabbing indices from {child.fullName} to {parent.fullName}
'''
      # now we have done the kernel for each children
      # we will need to do a kernel for total accumulation
      self.__kernelString += f'''
__device__ inline void {parent.fullName}_get_indices(
  {", ".join([f"const unsigned int* {x.fullName}_indices" for x in self.__used_join_attributes]) + ", " if self.__used_join_attributes else ""}
  {", ".join([f"const unsigned int* {x.correspondance.code_generation_counts_name}" for x in self.__used_union_attributes]) + ", " if self.__used_union_attributes else ""}
  const unsigned int* wrtStartIndices,
  unsigned int* outputIndices,
  unsigned short int* outputSizes,
  unsigned int index
){{
  // const int num_children = {len(self.__path_dict[parent])};
  // const int childrenIndexSizes[num_children] = {{{", ".join([str(self.__indexSizeForEachPart[x]) for x in self.__path_dict[parent]])}}}; // here we first know how much space to save for each child
  // we expand the for loop directly
'''
      index_accumulation: int = 0
      if parent.operator == UNION:
        self.__kernelString += f'''
  // we will actually check the index here? it's very cheap to do so
  unsigned int primitive_index = 0;
  unsigned int total_count = 0;
  for (unsigned int i = 0; i < {len(parent.children)}; i++){{
    if ((total_count + {parent.correspondance.code_generation_counts_name}[i]) > index) {{
      primitive_index = i;
      break;
    }}
    total_count += {parent.correspondance.code_generation_counts_name}[i];
  }}
  unsigned int shifted_index = index - total_count;
  switch(primitive_index){{
'''
        for (ind, child) in enumerate(parent.children):
          # we first need to determine for each child attribute
          # does it actually need to get some index
          # then we will grab all the indices needed for that child
          # we need to do a special case for union operator when parent is union
          # this is because our path dict construction never contain the direct child
          # of the union or join operator
          # we instead only stored the next join/union node
          # so we will need to manually determine which union's child needs to grab index
          used_grandchildren = []
          for grandchild in self.__path_dict[parent]:
            if grandchild in self.__unioned_child_to_its_children[child]:
              used_grandchildren.append(grandchild)
          self.__kernelString += f'''
    case {ind}:
      {{
        // we will add an index shift because there can be multiple indices
        // we need to grab for the same child
        unsigned int outputIndexShift = 0;
'''
          for used_grandchild in used_grandchildren:
            self.__kernelString += f'''
        {parent.fullName}_get_indices_from_{used_grandchild.fullName}(
          {", ".join([f"{x.fullName}_indices" for x in self.__used_join_attributes]) + ", " if self.__used_join_attributes else ""}
          {", ".join([f"{x.correspondance.code_generation_counts_name}" for x in self.__used_union_attributes]) + ", " if self.__used_union_attributes else ""}
          wrtStartIndices,
          outputIndices + outputIndexShift,
          outputSizes + outputIndexShift,
          shifted_index // use the shifted index instead of the original index since primitives are stacked in a union operation
        );
        outputIndexShift += {self.__indexSizeForEachPart[used_grandchild]};
'''
          self.__kernelString += '''
      }
      break;
'''
        self.__kernelString += f'''
    default:
      break;
  }} // end of switch
}} // end of kernel for grabbing indices from of {parent.fullName}
'''
      elif parent.operator == JOIN:
        self.__kernelString += f'''
  for (unsigned int i = 0; i < {parent.through.dimension}; i++){{
    unsigned int outputIndexShift = 0;
'''
        # we need special code for join operator
        # first we make a simple assertion, should always pass
        assert self.__indexSizeForEachPart[parent] % parent.through.dimension == 0, f"Index size {self.__indexSizeForEachPart[parent]} is not divisible by dimension {parent.through.dimension}"
        for ind in range(len(self.__path_dict[parent])):
          child = self.__path_dict[parent][ind]
          self.__kernelString += f'''
    {parent.fullName}_get_indices_from_{child.fullName}(
      {", ".join([f"{x.fullName}_indices" for x in self.__used_join_attributes]) + ", " if self.__used_join_attributes else ""}
      {", ".join([f"{x.correspondance.code_generation_counts_name}" for x in self.__used_union_attributes]) + ", " if self.__used_union_attributes else ""}
      wrtStartIndices,
      outputIndices + {index_accumulation} + {self.__indexSizeForEachPart[parent] // parent.through.dimension} * i,
      outputSizes + {index_accumulation} + {self.__indexSizeForEachPart[parent] // parent.through.dimension} * i,
      {(parent.fullName + f"_indices[index * {parent.through.dimension} + i]")}
    );
'''
          index_accumulation += self.__indexSizeForEachPart[child]
        assert index_accumulation == (self.__indexSizeForEachPart[parent]  // parent.through.dimension), f"Index size {index_accumulation} is not equal to {self.__indexSizeForEachPart[parent]} // {parent.through.dimension}"
        self.__kernelString += f'''
  }} // end of for loop for join
}} // end of kernel for grabbing indices from of {parent.fullName}
'''
      else:
        for ind in range(len(self.__path_dict[parent])):
          child = self.__path_dict[parent][ind]
          # call the function
          self.__kernelString += f'''
  // grab indices from child {child.fullName} to parent {parent.fullName}
  {parent.fullName}_get_indices_from_{child.fullName}(
    {", ".join([f"{x.fullName}_indices" for x in self.__used_join_attributes]) + ", " if self.__used_join_attributes else ""}
    {", ".join([f"{x.correspondance.code_generation_counts_name}" for x in self.__used_union_attributes]) + ", " if self.__used_union_attributes else ""}
    wrtStartIndices,
    outputIndices + {index_accumulation},
    outputSizes + {index_accumulation},
    index
  );
'''
          index_accumulation += self.__indexSizeForEachPart[child]
        self.__kernelString += f'''
}} // end of kernel for grabbing indices from of {parent.fullName}
'''

    # now we can do the global kernel
    self.__kernelString += f'''
__global__ void {self.__energy.fullName}_get_indices_global_function(
  {", ".join([f"const unsigned int* {x.fullName}_indices" for x in self.__used_join_attributes]) + ", " if self.__used_join_attributes else ""}
  {", ".join([f"const unsigned int* {x.correspondance.code_generation_counts_name}" for x in self.__used_union_attributes]) + ", " if self.__used_union_attributes else ""}
  const unsigned int* wrtStartIndices,
  unsigned int* outputIndices,
  unsigned short int* outputSizes,
  unsigned int NUM_INSTANCES
) {{
  unsigned int index = threadIdx.x + blockIdx.x * blockDim.x;
  if (index < NUM_INSTANCES) {{
    {self.__energy.fullName}_get_indices(
      {", ".join([f"{x.fullName}_indices" for x in self.__used_join_attributes]) + ", " if self.__used_join_attributes else ""}
      {", ".join([f"{x.correspondance.code_generation_counts_name}" for x in self.__used_union_attributes]) + ", " if self.__used_union_attributes else ""}
      wrtStartIndices,
      outputIndices + index * {self.maxNumIndicesNeeded},
      outputSizes + index * {self.maxNumIndicesNeeded},
      index
    );
  }}
}}
'''
    # now we do the function on c side
    self.__kernelString += f'''
// for checking cuda error
#define CUDA_CHECK_ERROR(ans)                                                  \
  {{ cudaAssert((ans), __FILE__, __LINE__); }}
inline void cudaAssert(cudaError_t code, const char *file, int line,
                        bool abort = true) {{
                        if (code != cudaSuccess) {{
    fprintf(stderr, "CUDA Error: %s at %s:%d\\n", cudaGetErrorString(code), file,
            line);
    if (abort)
      exit(code);
  }}
}}
extern "C" int get_indices(
  {", ".join([f"const unsigned int* {x.fullName}_indices" for x in self.__used_join_attributes]) + ", " if self.__used_join_attributes else ""}
  {", ".join([f"const unsigned int* {x.correspondance.code_generation_counts_name}" for x in self.__used_union_attributes]) + ", " if self.__used_union_attributes else ""}
  const unsigned int* wrtStartIndices,
  unsigned int* outputIndices,
  unsigned short int* outputSizes,
  unsigned int NUM_INSTANCES
) {{
  {self.__energy.fullName}_get_indices_global_function<<<(NUM_INSTANCES + 32 - 1) / 32, 32>>>(
    {", ".join([f"{x.fullName}_indices" for x in self.__used_join_attributes]) + ", " if self.__used_join_attributes else ""}
    {", ".join([f"{x.correspondance.code_generation_counts_name}" for x in self.__used_union_attributes]) + ", " if self.__used_union_attributes else ""}
    wrtStartIndices,
    outputIndices,
    outputSizes,
    NUM_INSTANCES
  );
  cudaError_t err = cudaDeviceSynchronize();
  if (err != cudaSuccess) {{
    fprintf(stderr, "CUDA Error (synchronize): %s\\n", cudaGetErrorString(err));
    return -1;
  }}
  return 0; // return success code
}}
'''

    # ok now we compile the kernel by saving it to a file and then calling nvcc
    file_name = f".yasps_tmp/{self.__energy.fullName}_get_indices_for_{'_'.join([x.fullName for x in self.__wrt])}"
    f = open(f"{file_name}.cu", 'w')
    self.__kernelString = prune_duplicate_functions(self.__kernelString) # just in case we have duplicated functions
    f.write(self.__kernelString)
    f.close()
    # we will now compile this kernel
    os.system(f"nvcc -Xcompiler -fPIC -shared -o {file_name}.so {file_name}.cu -O3 -arch=sm_86 -lcudart -lcuda")
    self.__indices_kernel = ctypes.CDLL(f"{file_name}.so").get_indices # get the compiled kernel
    self.__indices_kernel.restype = ctypes.c_int # set the return type to None
    self.__indices_kernel.argtypes = [ctypes.c_void_p] * len(self.__used_join_attributes) + [ctypes.c_void_p] * len(self.__used_union_attributes) + [ctypes.c_void_p] * 3 + [ctypes.c_uint32]


  @timed("gradientIndicesKernel.__reallocate")
  def __reallocate(self):
    newNumInstances: int = self.__energy.correspondance.numInstances
    if newNumInstances > self.__maxInstances:
      # resize the gpu arrays
      self.__outputIndices = gpuarray.empty(self.maxNumIndicesNeeded * newNumInstances, dtype=np.uint32)
      self.__outputIndexSizes = gpuarray.empty(self.maxNumIndicesNeeded * newNumInstances, dtype=np.uint16)
      self.__outputPermutations = gpuarray.empty(self.maxNumIndicesNeeded * newNumInstances, dtype=np.int16)
      self.__outputGradientSizes = gpuarray.empty(newNumInstances, dtype=np.uint16)
      self.__outputGroupedIndicesInner = gpuarray.empty(self.maxNumIndicesNeeded * newNumInstances, dtype=np.uint32)
      self.__outputCompressedCoordinateCountsOuter = gpuarray.empty(newNumInstances + 1, dtype=np.uint32)
      self.__maxInstances = newNumInstances # update the maximum size
    self.__numInstances = newNumInstances # update the number of instances
    if newNumInstances == 0:
      self.__numInstances = 0
      return
    # we clear the output arrays
    self.__outputIndices.fill(0)
    self.__outputIndexSizes.fill(0)
    self.__outputPermutations.fill(0)
    self.__outputGradientSizes.fill(0)
    self.__outputGroupedIndicesInner.fill(0)
    self.__outputUniqueGradientSizes.fill(0)
    self.__outputGroupedIndicesOuter.fill(0)
    self.__outputCompressedCoordinateCountsOuter.fill(0)

  @timed("gradientIndicesKernel.__computeIndices")
  def __computeIndices(self, wrt_start_indices: List[int]):
    # first let's convert wrt_start_indices to a pycuda array
    wrt_start_indices_gpu = gpuarray.to_gpu(np.array(wrt_start_indices, dtype=np.uint32)) # this has to be non empty
    # then we get all the gpu arrays for the connectivity
    connectivity_list_gpu = [self.__to_void_p(x.through.value) for x in self.__used_join_attributes]
    self.__union_counts = [x.correspondance.children_primitive_counts_gpu for x in self.__used_union_attributes]
    union_count_list_gpu = [self.__to_void_p(x) for x in self.__union_counts]
    # now we invoke the kernel

    assert self.__indices_kernel is not None
    error_code = self.__indices_kernel(
      *connectivity_list_gpu,
      *union_count_list_gpu,
      self.__to_void_p(wrt_start_indices_gpu),
      self.__to_void_p(self.__outputIndices),
      self.__to_void_p(self.__outputIndexSizes),
      self.__numInstances
    )

    if error_code != 0:
      raise RuntimeError(f"gradientIndiciesKernel.__computeIndices: Error in computing indices: {error_code}")

  @timed("gradientIndicesKernel.__compressIndicesLocal")
  def __compressIndicesLocal(self):
    assert self.__compression_kernel is not None
    error_code = self.__compression_kernel(
      self.__to_void_p(self.__outputIndices),
      self.__to_void_p(self.__outputIndexSizes),
      self.__to_void_p(self.__outputPermutations),
      self.__to_void_p(self.__outputGradientSizes),
      self.__to_void_p(self.__outputCompressedCoordinateCountsOuter),
      self.__to_void_p(self.__outputUniqueGradientSizes),
      self.__to_void_p(self.__outputGroupedIndicesInner),
      self.__to_void_p(self.__outputGroupedIndicesOuter),
      self.__to_void_p(self.__outputNumUniqueGradientSizes),
      self.__numInstances,
      self.maxNumIndicesNeeded)
    if error_code != 0:
      raise RuntimeError(f"gradientIndiciesKernel.__compressIndicesLocal: Error in compressing indices: {error_code}")


  @property
  def numTotalCoordinates(self) -> int:
    if self.__numInstances == 0:
      return 0
    result = np.empty(1, dtype=np.uint32)
    assert self.__outputCompressedCoordinateCountsOuter is not None
    cuda.memcpy_dtoh(result, int(self.__outputCompressedCoordinateCountsOuter.gpudata) + self.__numInstances * np.dtype(np.uint32).itemsize)
    # return int(self.__outputCompressedCoordinateCountsOuter[self.__numInstances])
    return int(result[0])

  @timed("gradientIndicesKernel.allocateSpaceForCoordinates")
  def __allocateSpaceForCoordinates(self):
    # first get the size required space
    spaceNeeded = self.numTotalCoordinates * 2
    # now determine if it is larger than what we currently have
    if spaceNeeded > self.__outputCoordinates.size:
      # here we will allocate more space than needed to avoid frequent reallocations
      self.__outputCoordinates = gpuarray.empty(int(spaceNeeded * 1), dtype=np.uint32)
      self.__outputBlockDimensions = gpuarray.empty(int(spaceNeeded * 1), dtype=np.uint16)
    # fill in 0
    self.__outputCoordinates.fill(0)
    self.__outputBlockDimensions.fill(0)

  @timed("gradientIndicesKernel.generateCoordinates")
  def __generateCoordinates(self):
    assert self.__coordinate_kernel is not None
    error_code = self.__coordinate_kernel(
      self.__to_void_p(self.__outputIndices),
      self.__to_void_p(self.__outputPermutations),
      self.__to_void_p(self.__outputIndexSizes),
      self.__to_void_p(self.__outputCoordinates),
      self.__to_void_p(self.__outputBlockDimensions),
      self.__to_void_p(self.__outputCompressedCoordinateCountsOuter),
      self.maxNumIndicesNeeded,
      self.__numInstances
    )
    if error_code != 0:
      raise RuntimeError(f"gradientIndiciesKernel.__generateCoordinates: Error in generating coordinates: {error_code}")


  @timed("gradientIndicesKernel.computeIndices")
  def computeIndices(self, wrt_start_indices: List[int]):
    self.__reallocate()
    if self.__numInstances == 0:
      return
    self.__computeIndices(wrt_start_indices)
    self.__compressIndicesLocal()
    self.__allocateSpaceForCoordinates()
    self.__generateCoordinates()
